kind: ConfigMap
apiVersion: v1
metadata:
  name: dex
data:
  config.yaml: |
    issuer: https://dex.example.com
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: https://dex.example.com/callback
        orgs:
          - name: my-github-org
    oauth2:
      skipApprovalScreen: true
    staticClients:
    - id: traefik-dex-auth
      redirectURIs:
      - 'https://auth.example.com/traefik-dex-auth/callback'
      name: traefik-dex-auth
      secret: some-random-secret # TODO: Change me!
