apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: dex-crt
  namespace: dex
spec:
  commonName: dex.example.com
  secretName: dex-cert
  dnsNames:
    - dex.example.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
