apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dex
  name: dex
  namespace: dex
spec:
  ports:
  - name: "5556"
    port: 5556
    protocol: TCP
    targetPort: 5556
  selector:
    app: dex
  type: ClusterIP
status:
  loadBalancer: {}
