apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: auth
  name: auth
  namespace: dex
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: auth
  type: NodePort
status:
  loadBalancer: {}
