apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth
  name: auth
  namespace: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth
    spec:
      containers:
      - image: dvitali/traefik-dex-auth:latest
        name: traefik-dex-auth
        imagePullPolicy: Always
        env:
          - name: DEX_URL
            value: https://dex.example.com
          - name: TDA_URL
            value: https://auth.example.com
          - name: PORT
            value: "8080"
          - name: GIN_MODE
            value: release
          - name: LOG_LEVEL
            value: debug
          - name: CLIENT_ID
            value: traefik-dex-auth
          - name: CLIENT_SECRET
            value: ZXhhbXBsZS1hcHAtc2VjcmV0
          - name: COOKIE_DOMAIN
            value: ".example.com"

        ports:
          - containerPort: 8080
            
        resources: {}
status: {}
